update tools

diff --git a/ansible4roule4menu/roles/testmenu/files/check4hardware-change b/ansible4roule4menu/roles/testmenu/files/check4hardware-change
--- a/ansible4roule4menu/roles/testmenu/files/check4hardware-change
+++ b/ansible4roule4menu/roles/testmenu/files/check4hardware-change
@@ -1,12 +1,27 @@
 #!/bin/bash
 
+# Farbdefinitionen für Ausgaben
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[0;34m'
+MAGENTA='\033[0;35m'
+CYAN='\033[0;36m'
+NC='\033[0m'  # No Color (reset)
+
 # File to store the previous hardware state
-PREV_HW_FILE="/home/ansible/prev_hw_info.txt"
+PREV_HW_FILE="prev_hw_info.txt"
 
 # Function to get current hardware information
 get_hw_info() {
     #sudo lshw -short
-    sudo lspci -vvv
+    sudo lspci -n
+
+    echo -n "Name: "; sudo dmidecode -s baseboard-product-name
+    echo -n "Baseboard Manufacturer: "; sudo dmidecode -s baseboard-manufacturer
+    echo -n "Baseboard Version (Rev): "; sudo dmidecode -s baseboard-version
+    echo -n "BIOS Build: "; sudo dmidecode -s bios-version
+    echo -n "BIOS Date: "; sudo dmidecode -s bios-release-date
 }
 
 # Function to update the hardware information
@@ -18,7 +33,7 @@ update_hw_info() {
 
 # Function to display help
 show_help() {
-    echo "Usage: $0 [OPTIONS]"
+    echo "Usage: $0 [OPTIONS]" 
     echo ""
     echo "Options:"
     echo "  -u, --update    Update the stored hardware information"
@@ -48,11 +63,15 @@ if [ -f "$PREV_HW_FILE" ]; then
     # Read the previous hardware information
     PREV_HW_INFO=$(cat "$PREV_HW_FILE")
 
+
     # Compare the current and previous hardware information
     if [ "$CURRENT_HW_INFO" != "$PREV_HW_INFO" ]; then
+        echo -e ${RED}'***** ERROR ! *****' 
         echo "Hardware changes detected:"
         diff <(echo "$PREV_HW_INFO") <(echo "$CURRENT_HW_INFO")
-        read 
+        echo -e ${NC}
+        # read 
+        exit 1 
     else
         echo "No hardware changes detected."
     fi
@@ -60,3 +79,5 @@ else
     echo "Previous hardware information not found. Creating a new one."
     update_hw_info
 fi
+
+
